"""alembic test on existing database tables

Revision ID: 143d2d182ed3
Revises: 
Create Date: 2022-01-18 11:37:16.748011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143d2d182ed3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
